[package]
name = "pe-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoded-pointer = { git = "https://github.com/Nordgaren/encoded-pointer.git" }
