pub const IMAGE_DOS_SIGNATURE: u16 = 0x5A4D;
pub const IMAGE_NT_SIGNATURE: u32 = 0x4550;

pub const IMAGE_DIRECTORY_ENTRY_ARCHITECTURE: u16 = 7;
pub const IMAGE_DIRECTORY_ENTRY_BASERELOC: u16 = 5;
pub const IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT: u16 = 11;
pub const IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR: u16 = 14;
pub const IMAGE_DIRECTORY_ENTRY_DEBUG: u16 = 6;
pub const IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT: u16 = 13;
pub const IMAGE_DIRECTORY_ENTRY_EXCEPTION: u16 = 3;
pub const IMAGE_DIRECTORY_ENTRY_EXPORT: u16 = 0;
pub const IMAGE_DIRECTORY_ENTRY_GLOBALPTR: u16 = 8;
pub const IMAGE_DIRECTORY_ENTRY_IAT: u16 = 12;
pub const IMAGE_DIRECTORY_ENTRY_IMPORT: u16 = 1;
pub const IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG: u16 = 10;
pub const IMAGE_DIRECTORY_ENTRY_RESOURCE: u16 = 2;
pub const IMAGE_DIRECTORY_ENTRY_SECURITY: u16 = 4;
pub const IMAGE_DIRECTORY_ENTRY_TLS: u16 = 9;

pub const DLL_PROCESS_ATTACH: u32 = 1;
pub const DLL_THREAD_ATTACH: u32 = 2;
pub const DLL_THREAD_DETACH: u32 = 3;
pub const DLL_PROCESS_DETACH: u32 = 0;

pub const IMAGE_REL_BASED_ABSOLUTE: u16 = 0;
pub const IMAGE_REL_BASED_HIGH: u16 = 1;
pub const IMAGE_REL_BASED_LOW: u16 = 2;
pub const IMAGE_REL_BASED_HIGHLOW: u16 = 3;
pub const IMAGE_REL_BASED_HIGHADJ: u16 = 4;
pub const IMAGE_REL_BASED_MACHINE_SPECIFIC_5: u16 = 5;
pub const IMAGE_REL_BASED_RESERVED: u16 = 6;
pub const IMAGE_REL_BASED_MACHINE_SPECIFIC_7: u16 = 7;
pub const IMAGE_REL_BASED_MACHINE_SPECIFIC_8: u16 = 8;
pub const IMAGE_REL_BASED_MACHINE_SPECIFIC_9: u16 = 9;
pub const IMAGE_REL_BASED_DIR64: u16 = 10;

pub const MAX_SECTION_HEADER_LEN: u32 = 16;

#[cfg(all(target_pointer_width = "64"))]
pub const IMAGE_ORDINAL_FLAG: usize = 0x8000000000000000;
#[cfg(all(target_pointer_width = "32"))]
pub const IMAGE_ORDINAL_FLAG: usize = 0x80000000;

pub const STATUS_SUCCESS: i32 = 0x00000000;
pub const STATUS_DELETE_PENDING: i32 = 0xC0000056_u32 as _;
pub const STATUS_INVALID_PARAMETER: i32 = 0xC000000D_u32 as _;

pub const STATUS_PENDING: i32 = 0x103;
pub const STATUS_END_OF_FILE: i32 = 0xC0000011_u32 as _;
pub const STATUS_NOT_IMPLEMENTED: i32 = 0xC0000002_u32 as _;

pub const IMAGE_NUMBEROF_DIRECTORY_ENTRIES: usize = 0x10;

pub const MAX_PATH: usize = 255;
